### ISSUE TITLE
We have a domain name! Now how do we connect it to our web service?

### ISSUE THREAD

**Issue by shpadoinklejoe** [CS480RocketMan/Parking-#6]
Our domain is cpparking.me.  Mike did have it up and running for a little, but now cpparking.me is broken (only cpparking.me:8080 currently works).

(For your reference: we also have an email address that we created to register the domain name.  it is rocketdongcs480@gmail.com)

**Comment by dave-luk** [comment]
For this, you need to do a few things:

1. Have a remote (not good idea to host on personal computer) [AWS etc] 
2. run the instance of (Python/Java) server
3. go to domain settings and set the redirection to the IP address of the remote
4. PROFIT

**Comment by anthonygraca** [comment]
You can use a Raspberry Pi as a server

**Comment by shpadoinklejoe** [comment]
This task needs to be re-categorized as How to Continuous Integration?
